# Generated by Django 5.1.2 on 2024-11-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
