# Generated by Django 5.1.2 on 2024-11-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pindorama', '0002_rename_tipo_tipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
