# Generated by Django 5.1.2 on 2024-11-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pindorama', '0003_formas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
