# Generated by Django 5.1.2 on 2024-11-04 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pindorama', '0004_origens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criatura', models.CharField(max_length=50)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='foto_perfil/%Y/%m/%d')),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas', to='pindorama.formas')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origens', to='pindorama.origens')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='pindorama.tipos')),
            ],
        ),
    ]
