# Generated by Django 5.1.2 on 2024-11-04 20:48

import django.db.models.deletion
import pindorama.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pindorama', '0005_criaturas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumCriaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=pindorama.models.upload_to_album)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('criatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='pindorama.criaturas')),
            ],
        ),
    ]
