# Generated by Django 5.1.2 on 2024-11-04 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pindorama', '0007_albumcriaturas_fonte'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendasCriaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('estoria', models.TextField()),
                ('fonte', models.CharField(max_length=100)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('criatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendas', to='pindorama.criaturas')),
            ],
        ),
    ]
