# Generated by Django 5.1.2 on 2024-11-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pindorama', '0009_alter_lendascriaturas_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='criaturas',
            name='etiquetas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='criaturas',
            name='modo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
