# Generated by Django 5.1.2 on 2024-11-18 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pindorama', '0011_alter_criaturas_modo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criaturas',
            name='etiquetas',
        ),
        migrations.CreateModel(
            name='EtiquetasCriaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(blank=True, max_length=100, null=True)),
                ('criatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='pindorama.criaturas')),
            ],
        ),
    ]
