# Generated by Django 5.1.2 on 2024-11-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pindorama', '0013_elementos_etiquetascriaturas_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquetascriaturas',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
